"""Ad dummy model.

Revision ID: c26aad740747
Revises: 04661a024bd5
Create Date: 2023-10-03 18:50:46.798955

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c26aad740747"
down_revision = "04661a024bd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
