# LOCAL DEV

version: "3.9"

services:
  db:
    image: postgres:16.2-bullseye
    hostname: db
    ports:
    - "5435:5432"   # NOTE: we bind 5435 to avoid conflicts with popular 5432 port
    env_file:
    - ./.env
    volumes:
    - objective_database_dev:/var/lib/postgresql/data

    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: objective:dev
    restart: "no"
    command: alembic upgrade head
    env_file:
    - ./.env
    environment:
      OBJECTIVE_DATABASE_HOST: db
      OBJECTIVE_DATABASE_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  certbot:
    image: certbot/certbot:latest
    env_file:
    - ./.env
    volumes:
    - ./certbot/www/:/var/www/certbot/:rw   # UNUSED folder is empty

      # NOTE
      # all generated keys and issued certificates can be found in /etc/letsencrypt/live/${domain}
    - ./certbot/conf/:/etc/letsencrypt/:rw

  nginx:
    image: nginx:1.19.3
    ports:
    - "9001:9001" # mock connection for objective.services:80/443
    - "9002:9002" # mock connection for staging.objective.services:80/443
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/conf.d/default.conf

      # frontend build
    - type: bind
      source: ./build
      target: /usr/share/nginx/html/

      # UNUSED folder is empty
    - type: bind
      source: ./certbot/www
      target: /var/www/certbot/

      # NOTE: certs
      #
      # - All generated certs can be found at certbot at /etc/letsencrypt/live/${domain}
      # - We bind those certs to local ./certbot/conf/ PATH
      # - And here we provide them to nginx to common /etc/letsencrypt/
    - type: bind
      source: ./certbot/conf/
      target: /etc/letsencrypt/

    depends_on:
    - migrator

  api:
    image: objective:dev
    ports:
      # NOTE
      # for debug or local dev proposes we bind 8020, but nginx 80/443 is used for production
    - "8020:8000"
    restart: always
    env_file:
    - ./.env
    environment:
      OBJECTIVE_HOST: 0.0.0.0
      OBJECTIVE_DATABASE_HOST: db
      OBJECTIVE_DATABASE_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  objective_database_dev:
    name: objective_database_dev
