"""add elements table

Revision ID: d1ce0fb7ac9a
Revises: 92b97ae79e17
Create Date: 2024-09-30 10:23:55.832501

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1ce0fb7ac9a"
down_revision: Union[str, None] = "92b97ae79e17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "element",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("updated", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("version_nonce", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("_json", sa.JSON(), nullable=False),
        sa.Column("_updated", sa.Integer(), nullable=False),
        sa.Column("_scene_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["_scene_id"],
            ["scene.id"],
            name=op.f("fk_element__scene_id_scene"),
        ),
        sa.PrimaryKeyConstraint("_scene_id", "id", name=op.f("pk_element")),
    )
    op.create_index(
        op.f("ix_element__scene_id"),
        "element",
        ["_scene_id"],
        unique=False,
    )
    op.alter_column(
        "file",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.drop_index("ix_file_file_id", table_name="file")
    op.drop_index("ix_file_scene_id", table_name="file")
    op.drop_constraint("uq_file_scene_id", "file", type_="unique")
    op.create_index(op.f("ix_file_created_at"), "file", ["created_at"], unique=False)
    op.create_index(op.f("ix_file_id"), "file", ["id"], unique=True)
    op.drop_constraint("file_scene_id_fkey", "file", type_="foreignkey")
    op.drop_column("file", "scene_id")
    op.drop_column("file", "file_id")
    op.create_index(
        op.f("ix_project_created_at"),
        "project",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_scene_created_at"), "scene", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scene_created_at"), table_name="scene")
    op.drop_index(op.f("ix_project_created_at"), table_name="project")
    op.add_column(
        "file",
        sa.Column("file_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "file",
        sa.Column("scene_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key("file_scene_id_fkey", "file", "scene", ["scene_id"], ["id"])
    op.drop_index(op.f("ix_file_id"), table_name="file")
    op.drop_index(op.f("ix_file_created_at"), table_name="file")
    op.create_unique_constraint("uq_file_scene_id", "file", ["scene_id", "file_id"])
    op.create_index("ix_file_scene_id", "file", ["scene_id"], unique=False)
    op.create_index("ix_file_file_id", "file", ["file_id"], unique=False)
    op.alter_column(
        "file",
        "id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.drop_index(op.f("ix_element__scene_id"), table_name="element")
    op.drop_table("element")
    # ### end Alembic commands ###
